# Form implementation generated from reading ui file 'D:\pyprojects\calibre\src\calibre\gui2\convert\structure_detection.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(657, 479)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.opt_page_breaks_before = XPathEdit(parent=Form)
        self.opt_page_breaks_before.setObjectName("opt_page_breaks_before")
        self.gridLayout.addWidget(self.opt_page_breaks_before, 7, 0, 2, 4)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 2)
        self.opt_chapter = XPathEdit(parent=Form)
        self.opt_chapter.setObjectName("opt_chapter")
        self.gridLayout.addWidget(self.opt_chapter, 0, 0, 1, 4)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 3, 1, 1)
        self.opt_chapter_mark = QtWidgets.QComboBox(parent=Form)
        self.opt_chapter_mark.setMinimumContentsLength(20)
        self.opt_chapter_mark.setObjectName("opt_chapter_mark")
        self.gridLayout.addWidget(self.opt_chapter_mark, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 6, 0, 1, 4)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem1, 10, 0, 1, 1)
        self.opt_insert_metadata = QtWidgets.QCheckBox(parent=Form)
        self.opt_insert_metadata.setObjectName("opt_insert_metadata")
        self.gridLayout.addWidget(self.opt_insert_metadata, 4, 0, 1, 1)
        self.opt_start_reading_at = XPathEdit(parent=Form)
        self.opt_start_reading_at.setObjectName("opt_start_reading_at")
        self.gridLayout.addWidget(self.opt_start_reading_at, 9, 0, 1, 4)
        self.opt_remove_fake_margins = QtWidgets.QCheckBox(parent=Form)
        self.opt_remove_fake_margins.setObjectName("opt_remove_fake_margins")
        self.gridLayout.addWidget(self.opt_remove_fake_margins, 5, 0, 1, 1)
        self.opt_remove_first_image = QtWidgets.QCheckBox(parent=Form)
        self.opt_remove_first_image.setObjectName("opt_remove_first_image")
        self.gridLayout.addWidget(self.opt_remove_first_image, 5, 1, 1, 1)
        self.opt_add_alt_text_to_img = QtWidgets.QCheckBox(parent=Form)
        self.opt_add_alt_text_to_img.setObjectName("opt_add_alt_text_to_img")
        self.gridLayout.addWidget(self.opt_add_alt_text_to_img, 4, 1, 1, 1)
        self.label.setBuddy(self.opt_chapter_mark)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):

        Form.setWindowTitle(_("Form"))
        self.label.setText(_("Chapter &mark:"))
        self.label_2.setText(_("The header and footer removal options have been replaced by the Search & replace options. Click the Search & replace category in the bar to the left to use these options. Leave the replace field blank and enter your header/footer removal regexps into the search field."))
        self.opt_insert_metadata.setText(_("Insert &metadata as page at start of book"))
        self.opt_remove_fake_margins.setText(_("Remove &fake margins"))
        self.opt_remove_first_image.setText(_("Remove first &image"))
        self.opt_add_alt_text_to_img.setText(_("Add &alt text to images"))
from calibre.gui2.convert.xpath_wizard import XPathEdit
